services:
  app:
    build: .
    container_name: bankvilage-app
    ports:
      - "3050:3000"
    env_file:
      - .env # อ้างอิงไปยังไฟล์ .env
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
